export const engineeringZh: Record<string, string> = {
  "Expand to full screen": "全屏展开",
  "Restore panel": "还原面板",
  "Open item BIM": "打开此资产 BIM",
  "Item BIM reference": "资产级 BIM 参考",
  "No component linked to this item": "此资产尚未关联构件",
  "Session reference only · not a verified equipment mapping":
    "仅本次会话参考关联 · 非经核验的设备映射",
  "Unlink reference": "解除参考关联",
  "Link component to this item": "将构件关联到此资产",
  "Update linked component and evidence": "更新关联构件及依据",
  "Linked BIM evidence included": "已附带此资产的 BIM 参考依据",
  "Diagnostic complete": "诊断已完成",
  ready: "方案就绪",
  blocked: "未准备可应用方案",
  investigating: "正在诊断",
  applied: "已应用",
  failed: "失败",
  "Circuit flow": "回路流量",
  "BIM work studio": "BIM 工作室",
  "BIM Studio": "BIM 工作室",
  "BIM WORK STUDIO": "BIM 工程工作室",
  "Engineering datasets": "工程数据集",
  "Mechanical BIM": "机电 BIM",
  "District topology": "区域管网拓扑",
  "Simulation & AI ↗": "仿真与智能体 ↗",
  "Sources & scope": "来源与范围",
  "PUBLIC ENGINEERING DEMONSTRATOR /": "公共工程示范 /",
  "PUBLISHED NETWORK GRAPH": "已发布管网拓扑",
  "FULL 3D": "全三维",
  "Imported MEP coordination model · source geometry and IFC identities retained":
    "导入机电协调模型 · 保留源几何与 IFC 标识",
  "OpenDHN / Verbier · 2 heat sources · 150 substations · independent network benchmark":
    "OpenDHN / Verbier · 2 个热源 · 150 个换热站 · 独立管网基准",
  "Import local GLB file": "导入本地 GLB 文件",
  "Checking file…": "正在检查文件…",
  "Import GLB": "导入 GLB",
  "Export review ↗": "导出审查记录 ↗",
  "Retry dataset load": "重新加载数据集",
  "Engineering datasets could not be loaded.": "无法加载工程数据集。",
  "Engineering geometry, not live equipment": "工程几何，非实时设备",
  "Topology analysis, not a safe-isolation procedure":
    "拓扑分析，非安全隔离操作规程",
  "No readings are assigned to imported components without a validated mapping.":
    "未经验证的映射，不会将读数分配给导入构件。",
  "Node coordinates are anonymised; elevations are absent and pipe glyph widths are exaggerated.":
    "节点坐标已匿名化；缺少高程，管线显示宽度经过放大。",
  "Asset register": "资产台账",
  "Find asset, name or IFC class": "搜索资产、名称或 IFC 类别",
  "Discipline / class": "专业 / 类别",
  "Filter asset class": "筛选资产类别",
  "All classes": "全部类别",
  "matches ·": "项匹配 ·",
  shown: "项显示",
  "Engineering asset list": "工程资产列表",
  "Supply pipe": "供水管",
  "Return pipe": "回水管",
  hidden: "已隐藏",
  "No assets match this filter.": "没有符合筛选条件的资产。",
  "Persistent source identity": "持久源标识",
  "Published graph parameters": "已发布拓扑参数",
  "IFC GlobalIds are retained through conversion. Local meshes without IDs use mesh names.":
    "转换时保留 IFC GlobalId。本地网格缺少标识时使用网格名称。",
  "Lengths, diameters and insulation are imported from the dataset—not derived from the display.":
    "长度、管径与保温参数来自数据集，非根据显示几何推断。",
  "Return to public BIM": "返回公共 BIM",
  "⊞ Fit all": "⊞ 适配全部",
  "⌑ Plan": "⌑ 平面视图",
  "⌖ Focus": "⌖ 聚焦",
  "↔ Measure": "↔ 测量",
  "◈ Isolate": "◈ 单独显示",
  "Show asset": "显示资产",
  "Hide asset": "隐藏资产",
  "⛶ Fullscreen": "⛶ 全屏",
  "Section plane": "剖切平面",
  "Section axis": "剖切轴",
  "X / longitudinal": "X / 纵向",
  "Y / horizontal": "Y / 水平",
  "Z / transverse": "Z / 横向",
  "Section position": "剖切位置",
  "No section": "不剖切",
  "Reset visibility": "重置可见性",
  "Measurement mode: select two visible mesh surfaces. Orbit first if necessary. Values describe tessellated geometry, not certified clearances.":
    "测量模式：选择两个可见网格表面，必要时先旋转视图。数值描述离散几何，非经认证的净距。",
  "Geometry review": "几何审查",
  "Pipe outage screen": "管段中断分析",
  "MODEL SPACE / METRES": "模型空间 / 米",
  "GRAPH CONNECTIVITY ONLY": "仅拓扑连通性",
  Measurements: "测量记录",
  "Select Measure, then pick two surfaces. The viewer records a 3D chord—not a pipe route length.":
    "选择测量后点击两个表面。记录三维直线距离，非管道路由长度。",
  "Surface-to-surface chord": "表面间直线距离",
  "Clear measurements": "清除测量",
  "Saved review views": "已保存审查视角",
  "+ Save current viewpoint": "+ 保存当前视角",
  "Viewpoints and notes are included in the JSON review export; they remain in memory until exported.":
    "视角和备注会包含在 JSON 审查导出中；导出前仅保存在本次会话内存中。",
  "Removed pipe edges": "移除的管段",
  "Disconnected substations": "失去连接的换热站",
  "Highlighted path length": "高亮路径长度",
  "The graph is treated as undirected. A substation is counted only if it had both source/return connectivity before the outage and loses either afterwards. No hydraulic redistribution, temperature or operational safety is inferred.":
    "按无向图分析。仅统计中断前供回水均与热源连通、中断后失去任一连接的换热站。不推断水力再分配、温度或运行安全。",
  "Clear all outages": "清除全部中断",
  "Disconnected:": "断开连接：",
  "Camera:": "相机：",
  loading: "加载中",
  "Y-up · model-space metres": "Y 轴向上 · 模型空间米制",
  "Plan layout only · no surveyed elevation": "仅平面布局 · 无实测高程",
  Inspect: "检查",
  "Review notes": "审查备注",
  "Asset review notes": "资产审查备注",
  "Record a question, missing parameter or coordination issue against the selected source asset.":
    "为所选源资产记录问题、缺失参数或协调事项。",
  "Note for": "备注对象",
  "no selection": "未选择",
  "e.g. Verify service clearance against the manufacturer manual.":
    "例如：根据厂家手册核查检修净距。",
  "Add review note": "添加审查备注",
  "SOURCE COMPONENT": "源构件",
  "NETWORK ASSET": "管网资产",
  "Select a component": "选择构件",
  "Select a pipe": "选择管段",
  "This asset is hidden from the viewport.": "此资产已从视口隐藏。",
  "Local GLB · scale not independently verified": "本地 GLB · 比例尚未独立验证",
  "Imported IFC geometry · source identity retained":
    "导入 IFC 几何 · 保留源标识",
  "IFC class / mesh class": "IFC 类别 / 网格类别",
  "Source EXPRESS ID": "源 EXPRESS 标识",
  "Not supplied": "未提供",
  Storey: "楼层",
  "Not assigned": "未分配",
  Systems: "系统",
  "No explicit group assignment": "无显式系统分组",
  "Axis-aligned model bounds": "轴对齐模型边界",
  "Bounding-box extents are not nominal product dimensions. Surface measurements depend on tessellation and source-model quality.":
    "包围盒尺寸并非产品公称尺寸。表面测量取决于网格细分与源模型质量。",
  "Connection evidence": "连接依据",
  "No explicit IFC port relation is available for this component. Visual contact does not establish a hydraulic connection.":
    "此构件没有显式 IFC 端口关系。视觉接触不代表水力连接。",
  "Telemetry: not mapped": "遥测：未映射",
  "No instruments are inferred from this mesh. The connected operations panel uses the selected simulator asset, not this reference component.":
    "不会根据网格推断仪表数据。关联运行面板使用所选仿真资产，而非此参考构件。",
  "IFC property sets": "IFC 属性集",
  "No property sets supplied by this mesh.": "此网格未提供属性集。",
  "Published parameter record ·": "已发布参数记录 ·",
  supply: "供水",
  return: "回水",
  circuit: "回路",
  "Inlet node": "入口节点",
  "Outlet node": "出口节点",
  "Source pipe length": "源数据管长",
  "Internal diameter": "内径",
  "Insulation thickness": "保温层厚度",
  "Internal roughness": "内壁粗糙度",
  "Pipe length is taken from the source record, not from the screen-space chord. Glyph widths are exaggerated for selection.":
    "管长取自源记录，非屏幕直线距离。显示宽度经过放大，便于选择。",
  "Topology tools": "拓扑工具",
  "Trace shortest source path": "追踪至热源的最短路径",
  "Restore this edge": "恢复此管段",
  "Test outage of this pipe": "测试此管段中断",
  "Outage testing removes a graph edge only. It does not close a valve or command equipment. The route tool uses the intact published graph and source lengths.":
    "中断测试仅移除图中的边，不关闭阀门或控制设备。路径工具使用完整的已发布拓扑与源长度。",
  "No live hydraulic state": "无实时水力状态",
  "This view audits the published graph. Flow and temperatures from the separate 12-building simulator are not overlaid onto this unrelated benchmark.":
    "此视图审查已发布拓扑，不会将十二栋建筑仿真的流量与温度叠加到无关的基准网络。",
  "Published substation endpoints": "已发布换热站端点",
  "Published heat-source endpoints": "已发布热源端点",
  "Current outage screen": "当前中断分析",
  "Graph connection lost": "拓扑连接丢失",
  "No added disconnection": "无新增断连",
  "This is a network-node glyph, not a geometric model of the installation. It has no inferred capacity, equipment arrangement or live readings.":
    "这是管网节点图形，非现场几何模型。不推断容量、设备布置或实时读数。",
  "Connected pipe records": "相连管段记录",
  "Select a connected pipe to inspect its parameters and test a graph outage.":
    "选择相连管段以检查参数并测试拓扑中断。",
  "Select a mesh or a pipe from the viewport or asset register to inspect its source data.":
    "从视口或资产台账选择网格或管段，检查源数据。",
  "Provenance & engineering limits": "数据来源与工程限制",
  "Close provenance": "关闭来源说明",
  "Source model ↗": "源模型 ↗",
  "Source representations": "源几何表示",
  Converted: "已转换",
  "Failed / omitted": "失败 / 省略",
  "Explicit IFC port connections in source:": "源数据中的显式 IFC 端口连接：",
  ". Unavailable links are never inferred from nearby geometry.":
    "。不会根据相邻几何推断缺失连接。",
  "Conversion omissions": "转换省略项",
  "District network benchmark": "区域管网基准",
  "Published dataset ↗": "已发布数据集 ↗",
  "Data boundaries": "数据边界",
  "These two public datasets are independent. They are not represented as a connected installation, a manufacturer-certified heating station or a calibrated Chinese secondary-network twin. The operations context links to the synthetic district without assigning its readings to these components.":
    "两个公共数据集彼此独立，不代表相连设施、厂家认证供热站或经过校准的中国二次网孪生。运行上下文关联到合成片区，但不会将片区读数分配给这些构件。",
  "Local imports": "本地导入",
  "Self-contained uncompressed GLB, up to 50 MiB, is parsed in this browser. The file is not uploaded. GLB uses metres by convention, but its authoring scale and asset identities require verification. External resources and unsupported compression are rejected. Convert other IFC files offline with IfcOpenShell/IfcConvert, retaining metre units and GlobalIds. The supplied reproducibility script is pinned to the credited public benchmark; it must not misattribute another site.":
    "在浏览器内解析不超过 50 MiB 的自包含、未压缩 GLB，不上传文件。GLB 通常使用米，但建模比例与资产标识需验证。拒绝外部资源与不支持的压缩。其他 IFC 文件可使用 IfcOpenShell/IfcConvert 离线转换，保留米制单位与 GlobalId。提供的复现脚本仅适用于标明来源的公共基准，不可将其他场地错误归属到该来源。",
  "Industrial deployment gate": "工业部署前提",
  "Site geometry, reconciled asset IDs, validated connectivity, equipment curves, sensor quality, model calibration, access control and engineering sign-off are required before operational reliance. These tools support review; they do not issue a permit, certify clearances or control a plant.":
    "用于实际运行前，需具备现场几何、对齐的资产标识、经验证的连接、设备曲线、传感器质量、模型校准、访问控制和工程签核。工具仅支持审查，不签发许可、认证净距或控制现场设备。",
  "Connected heat supply chain": "关联供热链路",
  "SHARED OPERATING CONTEXT": "共享运行上下文",
  Revision: "版本",
  "Synthetic readings · reference geometry is not instrumented":
    "合成读数 · 参考几何未绑定仪表",
  "Heat supply chain": "供热链路",
  "ST01 · Energy centre": "ST01 · 能源中心",
  "Supply temperature": "供水温度",
  "Connected buildings": "相连建筑",
  "Selection follows the district supply chain. BIM picks remain separate reference identities; geometry alone cannot establish a hydraulic connection.":
    "选择沿片区供热链路联动。BIM 选择仍是独立参考标识，仅凭几何不能建立水力连接。",
  "Operate selected circuit in 3D": "在三维中操作所选回路",
  "GEOMETRY REVIEW → AGENT → VERIFIED SIMULATION":
    "几何审查 → 智能体 → 已验证仿真",
  "The agent receives the selected circuit, source component, review notes and surface measurements alongside current physical evidence.":
    "智能体同时接收所选回路、源构件、审查备注、表面测量与当前物理依据。",
  "Investigate with BIM evidence": "结合 BIM 依据诊断",
  "Plan supply-chain intervention": "规划供热链路干预",
  "Review mission & simulation plan": "查看任务与仿真方案",
  "Configure the AI provider in Connections to run an agent. Numerical controls remain available.":
    "请在连接面板配置 AI 服务以运行智能体。仍可使用数值控制。",
  "Shared agent mission": "共享智能体任务",
  "Agent tool activity": "智能体工具活动",
  "Validating BIM review and circuit context": "验证 BIM 审查与回路上下文",
  "Review the attached engineering evidence against the selected heat supply circuit. Distinguish reference geometry from simulated operation; test a relevant physical hypothesis and propose a verified intervention only if supported.":
    "结合附带工程依据审查所选供热回路。区分参考几何与仿真运行，测试相关物理假设，仅在有依据时提出经过验证的干预。",
};
