import type { Language } from './domain';

// The parity test in scripts/p0-invariants.ts treats this object as the
// contract for every user-visible string in the prototype.
export const copy: Record<Language, Record<string, string>> = {
  en: {
    overview: 'Overview', simulation: 'Simulation', forecast: 'Forecast', results: 'Results', settings: 'Settings',
    productTitle: 'AI Heating Optimisation Digital Twin', productSubtitle: 'Real-time simulation and AI-driven optimisation of secondary heating networks',
    scenario: 'Scenario', controlMode: 'Control Mode', traditional: 'Traditional Weather Compensation', advisory: 'AI Advisory', optimised: 'AI Optimised (MPC)',
    environment: 'Simulation Environment', simulationTime: 'Simulation Time', rapid: 'Rapid Daytime Warming', fixture: 'Fixture / mock data · no real equipment control', liveFixture: 'Live fixture', staticPrototype: 'Static prototype · fixture-backed', playback: 'Digital twin playback', configuration: 'Configuration shell',
    outdoor: 'Outdoor Temperature', solarRadiation: 'Solar Radiation', windSpeed: 'Wind Speed', requiredHeat: 'Required Heat Load', currentSupply: 'Current Heat Supply', plannedSupply: 'Planned Heat Supply', compliance: 'Compliance Rate ≥18°C', comfort: 'Comfort Rate 20–22°C', overheating: 'Overheating Rate >23°C', underheating: 'Underheating Rate <18°C',
    pumpPower: 'Pump Power', pumpElectricity: 'Pump Electricity', oversupply: 'Avoidable Oversupply', secondaryNetwork: 'Secondary Heating Network Digital Twin', supply: 'Secondary Supply Temperature', return: 'Secondary Return Temperature', totalFlow: 'Total Flow', pressure: 'Differential Pressure', pumpFrequency: 'Pump Frequency',
    near: 'Near Zone', mid: 'Mid Zone', far: 'Far Zone', primaryNetwork: 'Primary Network', substation: 'Heating Substation', supplyHot: 'Supply (Hot)', returnCold: 'Return (Cold)', systemStatus: 'System Status', operating: 'Operating Normally', nextForecast: 'Next 2h Forecast', riskOver: 'Buildings at risk of overheating (>23°C)', riskUnder: 'Buildings at risk of underheating (<18°C)', estimatedDelay: 'Estimated Transport Delay', thermalState: 'Thermal State', thermalCold: 'Cold', thermalCool: 'Cool', thermalComfort: 'Comfort', thermalWarm: 'Warm', thermalOverheated: 'Overheated',
    simulationDescription: 'Explore the digital twin playback and see how heating controls affect the secondary network.', recommendation: 'AI Recommendation', recommendationText: 'Reduce secondary supply temperature while redistributing zone flow.', apply: 'Apply to Simulation', applyDone: 'Recommendation applied', mpcActive: 'MPC Active', autoApplied: 'Auto-applied', noAutoChanges: 'Comparison only · no automatic control changes', currentIndoor: 'Current Indoor Temperature', predictedIndoor: 'Predicted Indoor Temperature', zoneFlow: 'Zone Flow', valve: 'Valve Opening', transportDelay: 'Transport Delay', events: 'Simulation Event Log', clear: 'Clear All', close: 'Close', selectedBuilding: 'Building Detail',
    alerts: 'Alerts & Insights', windowRisk: 'Simulated window-opening risk', farRisk: 'Far-zone temperatures remain lower than target', farRiskText: 'Consider increasing flow to improve comfort.', allBuildingsAboveCompliance: 'All buildings are above 18°C (100% compliance).', outdoorVsSupply: 'Outdoor Temperature vs Secondary Supply Temperature', distribution: 'Indoor Temperature Distribution', heatLoadVsSupply: 'Required Heat Load vs Actual Heat Supply', indoorByZone: 'Indoor Temperature Forecast by Zone', pumpTrend: 'Pump Power / Energy Trend', valveTrend: 'Zone Valve Opening', play: 'Play', pause: 'Pause', step: 'Step', reset: 'Reset', speed: 'Simulation Speed', hours: 'hours', minutes: 'minutes', point: 'point', fixtureData: 'Static fixture data', modelNames: 'Prediction model names are taxonomy labels',
    forecastTitle: 'Demand and comfort forecast', forecastDescription: 'Explain what the selected horizon means for load, comfort, and risk.', asOf: 'Forecast as of {time}', next6: 'Next 6 Hours', next24: 'Next 24 Hours', next48: 'Next 48 Hours', outdoorForecastTitle: 'Outdoor Temperature Forecast (Next {hours} Hours)', historicalPast: 'Historical (past 6h)', forecastNext: 'Forecast (next {hours}h)', plannedVsRequired: 'Required Heat Load vs Planned Heat Supply', indoorForecast: 'Predicted Indoor Temperature (Average of All Buildings)', comfortRange: 'Comfort Range (20–22°C)', distributionAt: 'Indoor Temperature Distribution at Selected Time', distributionAtTarget: 'Predicted Indoor Temperature Distribution at Forecast Target · {time}', insights: 'Forecast Insights', keyForecastMetrics: 'Key Forecast Metrics', confidence: 'Confidence', interval: '95% Prediction Interval', buildingForecast: 'Building-Level Forecast (Next {hours} Hours)', building: 'Building', area: 'Area (m²)', year: 'Year', insulation: 'Insulation', zone: 'Network Zone', risk: 'Risk', currentTemp: 'Current Temp', predictedTraditional: 'Predicted Traditional', predictedAi: 'Predicted AI', comfortable: 'Comfortable', watch: 'Watch', riskOverheating: 'Overheating', riskUnderheating: 'Underheating', numberOfBuildings: 'Number of Buildings', predictedCompliance: 'Predicted Compliance ≥18°C', predictedOverheating: 'Buildings at Risk of Overheating (>23°C)', predictedUnderheating: 'Buildings at Risk of Underheating (<18°C)', predictedComfort: 'Predicted Comfort Range (20–22°C)',
    rapidWarmingInsightTitle: 'Rapid daytime warming', rapidWarmingInsightText: 'Outdoor temperature is forecast to rise from −2.0°C to 4.5°C over the selected horizon.', solarInsightTitle: 'Solar gains reduce heating demand', solarInsightText: 'Increased solar radiation provides passive heat gains during daytime hours.', overheatingInsightTitle: 'Overheating risk in high-insulation buildings', overheatingInsightText: 'Near-zone high-insulation buildings are more exposed to solar gains.', farInsightTitle: 'Far-zone vulnerability remains', farInsightText: 'Far-zone buildings may remain at risk of underheating due to network distance.', forecastBoundary: 'Forecast boundary', forecastBoundaryText: 'Weather is an external forecast input. The prototype AI layer forecasts required heat load and indoor risk from fixture data; no production inference is running.',
    resultsTitle: 'Traditional vs AI Optimised · KPI Comparison', resultsDescription: 'A comparison of supply, comfort, balance, and simulated behavioural outcomes.', traditionalShort: 'Traditional', optimisedShort: 'AI Optimised (MPC)', heatConsumption: 'Heat Consumption (Total)', hydraulic: 'Hydraulic Balance Index', flowDistribution: 'Zone Flow Distribution (Hydraulic Comparison)', simulatedWindows: 'Simulated Window-opening Events', valuePerMetric: 'Value (same units per metric)', flowRate: 'Flow rate (m³/h)', eventsCount: 'Number of events', modelComparison: 'Heat Load Prediction Model Comparison', heldOut: 'Validation on held-out simulation scenarios', model: 'Model', mae: 'MAE (MW)', rmse: 'RMSE (MW)', r2: 'R²', simulationOnly: 'Simulation only · estimated behavioural response, not real detection.', modelNote: 'This table evaluates heat-load prediction models only. Building thermal models (RC / 2R2C) are calibrated and validated separately.', explanation: 'AI did not simply reduce total heat. It redistributed heat from overheated near-zone buildings to underheated far-zone buildings, while reducing overall oversupply.',
    settingsTitle: 'Prototype Settings', settingsDescription: 'P0 settings are a transparent fixture shell. Limits are shared with Simulation controls.', fixtureProfile: 'P0 fixture profile', targets: 'Targets & Thresholds', comfortTarget: 'Comfort Target Range', complianceThreshold: 'Compliance Threshold', overheatThreshold: 'Overheating Threshold', horizon: 'Forecast Horizon', controlStep: 'Control Step', limits: 'Equipment Limits', limitsNote: 'Single source of truth for Simulation controls and future MPC', nominalDelays: 'Nominal Transport Delay Profile', displayOnly: 'Display-only fixture value', weights: 'Objective Weights', objectiveCompliance: 'Compliance', objectiveComfort: 'Comfort', objectiveOversupply: 'Oversupply', objectivePump: 'Pump Energy', objectiveMovement: 'Control Movement', maxStep: 'Max step', high: 'High', medium: 'Medium', low: 'Low', radiator: 'Radiator', districtHeating: 'District Heating', version: 'Version',
    eventSimulationStarted: 'Simulation started', eventSimulationReset: 'Simulation reset', eventControlModeChanged: 'Control mode changed', eventMpcRecommendationGenerated: 'MPC recommendation generated', eventMpcControlAutoApplied: 'MPC control auto-applied', eventRecommendationApplied: 'Recommendation applied', eventSimulationStep: 'Simulation step', detailScenario: 'Scenario: Rapid Daytime Warming', detailFixturePlanReady: 'Fixture control plan ready', detailOptimisedActive: 'AI Optimised (MPC) active', detailOperatorConfirmed: 'Operator confirmed AI Advisory recommendation', detailTimelineFrame: 'Timeline frame {time}', detailSimulationReset: 'Canonical initial state restored', detailMode: '{mode}',
  },
  zh: {
    overview: '总览', simulation: '仿真', forecast: '预测', results: '结果', settings: '设置', productTitle: 'AI 供热优化数字孪生', productSubtitle: '二次供热网络的实时仿真与 AI 驱动优化', scenario: '场景', controlMode: '控制模式', traditional: '传统气候补偿控制', advisory: 'AI 辅助建议', optimised: 'AI 优化控制（MPC）', environment: '仿真环境', simulationTime: '仿真时间', rapid: '快速日间升温', fixture: 'Fixture / 模拟数据 · 不控制真实设备', liveFixture: '实时 Fixture', staticPrototype: '静态原型 · Fixture 数据', playback: '数字孪生回放', configuration: '配置壳',
    outdoor: '室外温度', solarRadiation: '太阳辐射', windSpeed: '风速', requiredHeat: '所需热负荷', currentSupply: '当前供热量', plannedSupply: '计划供热量', compliance: '供热达标率 ≥18°C', comfort: '舒适率 20–22°C', overheating: '过热率 >23°C', underheating: '欠热率 <18°C', pumpPower: '循环泵功率', pumpElectricity: '循环泵耗电量', oversupply: '可避免的过量供热', secondaryNetwork: '二次供热管网数字孪生', supply: '二次供水温度', return: '二次回水温度', totalFlow: '总流量', pressure: '压差', pumpFrequency: '循环泵频率', near: '近端区域', mid: '中端区域', far: '远端区域', primaryNetwork: '一次网', substation: '换热站', supplyHot: '供水（热）', returnCold: '回水（冷）', systemStatus: '系统状态', operating: '运行正常', nextForecast: '未来 2 小时预测', riskOver: '过热风险楼栋（>23°C）', riskUnder: '欠热风险楼栋（<18°C）', estimatedDelay: '估算输运延迟', thermalState: '室温状态', thermalCold: '欠热', thermalCool: '偏冷', thermalComfort: '舒适', thermalWarm: '偏暖', thermalOverheated: '过热',
    simulationDescription: '通过数字孪生回放观察供热控制对二次网和建筑状态的影响。', recommendation: 'AI 建议', recommendationText: '降低二次供水温度，同时重新分配区域流量。', apply: '应用到仿真', applyDone: '建议已应用', mpcActive: 'MPC 激活', autoApplied: '自动应用', noAutoChanges: '仅作对比 · 不自动改变控制', currentIndoor: '当前室内温度', predictedIndoor: '预测室内温度', zoneFlow: '区域流量', valve: '阀门开度', transportDelay: '输运延迟', events: '仿真事件日志', clear: '清空全部', close: '关闭', selectedBuilding: '楼栋详情', alerts: '告警与洞察', windowRisk: '模拟开窗风险', farRisk: '远端区域温度仍低于目标', farRiskText: '可考虑增加流量以改善舒适度。', allBuildingsAboveCompliance: '全部楼栋高于 18°C（100% 达标）。', outdoorVsSupply: '室外温度与二次供水温度', distribution: '室内温度分布', heatLoadVsSupply: '所需热负荷与实际供热量', indoorByZone: '按区域预测室内温度', pumpTrend: '循环泵功率 / 能耗趋势', valveTrend: '区域阀门开度', play: '播放', pause: '暂停', step: '步进', reset: '重置', speed: '仿真速度', hours: '小时', minutes: '分钟', point: '点', fixtureData: '静态 Fixture 数据', modelNames: '预测模型名称为分类标签',
    forecastTitle: '需求与舒适度预测', forecastDescription: '解释所选预测时域对负荷、舒适度和风险的影响。', asOf: '预测基准时间：{time}', next6: '未来 6 小时', next24: '未来 24 小时', next48: '未来 48 小时', outdoorForecastTitle: '室外温度预测（未来 {hours} 小时）', historicalPast: '历史（过去 6 小时）', forecastNext: '预测（未来 {hours} 小时）', plannedVsRequired: '所需热负荷与计划供热量', indoorForecast: '预测室内温度（全部楼栋平均）', comfortRange: '舒适区间（20–22°C）', distributionAt: '选定时刻的室内温度分布', distributionAtTarget: '预测目标时刻室温分布 · {time}', insights: '预测洞察', keyForecastMetrics: '关键预测指标', confidence: '置信度', interval: '95% 预测区间', buildingForecast: '楼栋级预测（未来 {hours} 小时）', building: '楼栋', area: '面积（m²）', year: '建成年代', insulation: '保温', zone: '网络区域', risk: '风险', currentTemp: '当前温度', predictedTraditional: '传统预测', predictedAi: 'AI 预测', comfortable: '舒适', watch: '关注', riskOverheating: '过热', riskUnderheating: '欠热', numberOfBuildings: '楼栋数量', predictedCompliance: '预测达标率 ≥18°C', predictedOverheating: '过热风险楼栋（>23°C）', predictedUnderheating: '欠热风险楼栋（<18°C）', predictedComfort: '预测舒适区间（20–22°C）', rapidWarmingInsightTitle: '快速日间升温', rapidWarmingInsightText: '在所选时域内，室外温度预计从 −2.0°C 上升至 4.5°C。', solarInsightTitle: '太阳得热降低供热需求', solarInsightText: '日间增强的太阳辐射可提供被动得热。', overheatingInsightTitle: '高保温楼栋存在过热风险', overheatingInsightText: '近端高保温楼栋更容易受到太阳得热影响。', farInsightTitle: '远端区域仍较脆弱', farInsightText: '受网络距离影响，远端楼栋仍可能存在欠热风险。', forecastBoundary: '预测边界', forecastBoundaryText: '天气是外部预测输入。原型 AI 层基于 Fixture 数据预测所需热负荷和室内风险；当前未运行生产推理。',
    resultsTitle: '传统控制 vs AI 优化 · KPI 对比', resultsDescription: '对比供热、舒适度、水力平衡和模拟行为结果。', traditionalShort: '传统控制', optimisedShort: 'AI 优化控制（MPC）', heatConsumption: '总热耗', hydraulic: '水力平衡指数', flowDistribution: '区域流量分布（水力对比）', simulatedWindows: '模拟开窗事件', valuePerMetric: '数值（按指标使用对应单位）', flowRate: '流量（m³/h）', eventsCount: '事件数量', modelComparison: '热负荷预测模型对比', heldOut: '基于留出仿真场景的验证', model: '模型', mae: 'MAE（MW）', rmse: 'RMSE（MW）', r2: 'R²', simulationOnly: '仅仿真 · 模拟行为响应，并非真实检测。', modelNote: '此表仅评估热负荷预测模型。建筑热模型（RC / 2R2C）单独校准与验证。', explanation: 'AI 并非简单减少总热量，而是将热量从过热的近端楼栋重新分配到欠热的远端楼栋，同时减少整体过量供热。',
    settingsTitle: '原型设置', settingsDescription: 'P0 设置是透明的 Fixture 配置壳。限制与仿真控制共用。', fixtureProfile: 'P0 Fixture 配置', targets: '目标与阈值', comfortTarget: '舒适目标区间', complianceThreshold: '达标阈值', overheatThreshold: '过热阈值', horizon: '预测时域', controlStep: '控制步长', limits: '设备边界', limitsNote: '仿真控制与未来 MPC 的单一事实来源', nominalDelays: '名义输运延迟配置', displayOnly: '仅用于展示的 Fixture 数值', weights: '目标权重', objectiveCompliance: '达标率', objectiveComfort: '舒适度', objectiveOversupply: '过量供热', objectivePump: '泵能耗', objectiveMovement: '控制动作幅度', maxStep: '最大步长', high: '高', medium: '中', low: '低', radiator: '散热器', districtHeating: '区域供热', version: '版本',
    eventSimulationStarted: '仿真已开始', eventSimulationReset: '仿真已重置', eventControlModeChanged: '控制模式已变更', eventMpcRecommendationGenerated: 'MPC 建议已生成', eventMpcControlAutoApplied: 'MPC 控制已自动应用', eventRecommendationApplied: '建议已应用', eventSimulationStep: '仿真步进', detailScenario: '场景：快速日间升温', detailFixturePlanReady: 'Fixture 控制计划已就绪', detailOptimisedActive: 'AI 优化控制（MPC）已激活', detailOperatorConfirmed: '操作员已确认 AI 辅助建议', detailTimelineFrame: '时间线帧：{time}', detailSimulationReset: '已恢复规范初始状态', detailMode: '{mode}',
  },
};

export function translate(language: Language, key: string): string { return copy[language][key] ?? copy.en[key] ?? key; }
